AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - script/**/*
    - log/**/*
    - test/**/*
    - app/validators/**
Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Next: 
  Enabled: false
Metrics/LineLength:
  Max: 105
Rails:
  Enabled: true
RedundantSelf: 
  Enabled: false
Style/TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-whitespace'
  Enabled: true
StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
Style/FileName:
  Enabled: false
Style/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false
Metrics/MethodLength:
  Max: 25
