# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8078fdd31ba1e3ca3ea2a1e321fa0b0a758d1fc736fb0cbb02e1dba91457cfdcf0d6b5f729f889d11d82b79bb94192fb21ac9c4b41e51b63fe4d97932ad6e77e

test:
  secret_key_base: 9e845fed78f49cbf67f7eb44cf4dc90925fb29e22034e66d1af5776d4f8295cb777c7e71fbfc25f3ca15ef3bc16f2a148c0b39266b936b42c5e380f046386a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
